module.exports = {
    admin: {
        username: process.env.E2E_ADMIN_USERNAME,
        password: process.env.E2E_ADMIN_PASSWORD,
        main_garden_name: process.env.E2E_ADMIN_MAIN_GARDEN_NAME,
        subgarden_name: process.env.E2E_ADMIN_SUBGARDEN_NAME,
        main_garden_id: process.env.E2E_ADMIN_MAIN_GARDEN_ID,
        subgarden_id: process.env.E2E_ADMIN_SUBGARDEN_ID,
    }, multiple_gardens: {
        username: process.env.E2E_MULTIPLE_GARDENS_USERNAME,
        password: process.env.E2E_MULTIPLE_GARDENS_PASSWORD,
        main_garden_name: process.env.E2E_MULTIPLE_GARDENS_MAIN_GARDEN_NAME,
        subgarden_name: process.env.E2E_MULTIPLE_GARDENS_SUBGARDEN_NAME,
        main_garden_id: process.env.E2E_MULTIPLE_GARDENS_MAIN_GARDEN_ID,
        subgarden_id: process.env.E2E_MULTIPLE_GARDENS_SUBGARDEN_ID,
    }, user: {
        username: process.env.E2E_USER_USERNAME,
        password: process.env.E2E_USER_PASSWORD,
        main_garden_name: process.env.E2E_USER_MAIN_GARDEN_NAME,
        subgarden_name: process.env.E2E_USER_SUBGARDEN_NAME,
        main_garden_id: process.env.E2E_USER_MAIN_GARDEN_ID,
        subgarden_id: process.env.E2E_USER_SUBGARDEN_ID,
    }, no_subgarden: {
        username: process.env.E2E_NO_SUBGARDEN_USERNAME,
        password: process.env.E2E_NO_SUBGARDEN_PASSWORD,
        main_garden_name: process.env.E2E_NO_SUBGARDEN_MAIN_GARDEN_NAME,
        subgarden_name: process.env.E2E_NO_SUBGARDEN_SUBGARDEN_NAME,
        main_garden_id: process.env.E2E_NO_SUBGARDEN_MAIN_GARDEN_ID,
        subgarden_id: process.env.E2E_NO_SUBGARDEN_SUBGARDEN_ID,
    }, main_garden: {
        username: process.env.E2E_MAIN_GARDEN_USERNAME,
        password: process.env.E2E_MAIN_GARDEN_PASSWORD,
        main_garden_name: process.env.E2E_MAIN_GARDEN_MAIN_GARDEN_NAME,
        subgarden_name: process.env.E2E_MAIN_GARDEN_SUBGARDEN_NAME,
        main_garden_id: process.env.E2E_MAIN_GARDEN_MAIN_GARDEN_ID,
        subgarden_id: process.env.E2E_MAIN_GARDEN_SUBGARDEN_ID,
    }, add_admin: {
        username: process.env.E2E_ADD_ADMIN_USERNAME,
        password: process.env.E2E_ADD_ADMIN_PASSWORD,
        main_garden_name: process.env.E2E_ADD_ADMIN_MAIN_GARDEN_NAME,
        subgarden_name: process.env.E2E_ADD_ADMIN_SUBGARDEN_NAME,
        main_garden_id: process.env.E2E_ADD_ADMIN_MAIN_GARDEN_ID,
        subgarden_id: process.env.E2E_ADD_ADMIN_SUBGARDEN_ID,
    }, add_user: {
        username: process.env.E2E_ADD_USER_USERNAME,
        password: process.env.E2E_ADD_USER_PASSWORD,
        main_garden_name: process.env.E2E_ADD_USER_MAIN_GARDEN_NAME,
        subgarden_name: process.env.E2E_ADD_USER_SUBGARDEN_NAME,
        main_garden_id: process.env.E2E_ADD_USER_MAIN_GARDEN_ID,
        subgarden_id: process.env.E2E_ADD_USER_SUBGARDEN_ID,
    },
}
