# Generated by Django 3.1.13 on 2021-10-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('staff', 'staff'), ('student', 'student')], max_length=255, verbose_name='Status of Member'),
        ),
    ]
