# Generated by Django 3.1.13 on 2022-01-14 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0001_initial'),
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Date and time of collection')),
                ('doy', models.IntegerField(help_text='Day of year')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.garden')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_entry', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of record entry')),
                ('timestamp_edit', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of record edit')),
                ('initial_vegetative_growth', models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no'), ('u', 'unsure'), ('m', 'missed')], max_length=2, null=True)),
                ('young_leaves_unfolding', models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no'), ('u', 'unsure'), ('m', 'missed')], max_length=2, null=True)),
                ('flowers_open', models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no'), ('u', 'unsure')], max_length=2, null=True)),
                ('peak_flowering', models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no'), ('u', 'unsure')], max_length=2, null=True)),
                ('flowering_intensity', models.IntegerField(blank=True, null=True)),
                ('ripe_fruits', models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no'), ('u', 'unsure')], max_length=2, null=True)),
                ('senescence', models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no'), ('u', 'unsure')], max_length=2, null=True)),
                ('senescence_intensity', models.IntegerField(blank=True, null=True)),
                ('maintenance', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cut_partly', 'cut partly'), ('cut_total', 'cut total'), ('covered_natural', 'covered natural'), ('covered_artificial', 'covered artificial'), ('transplanted', 'transplanted'), ('removed', 'removed')], max_length=120, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('peak_flowering_estimation', models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no')], max_length=2, null=True)),
                ('done', models.BooleanField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.collection')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
    ]
