# Generated by Django 3.1.13 on 2021-09-06 13:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardens', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, help_text='Date and time of collection')),
                ('doy', models.IntegerField(help_text='Day of year')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.garden')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_entry', models.DateTimeField(default=datetime.datetime.now, help_text='Date and time of record entry')),
                ('timestamp_edit', models.DateTimeField(default=datetime.datetime.now, help_text='Date and time of record edit')),
                ('initial_vegetative_growth', models.BooleanField(null=True)),
                ('young_leaves_unfolding', models.BooleanField(null=True)),
                ('flowers_open', models.BooleanField(null=True)),
                ('peak_flowering', models.BooleanField(null=True)),
                ('flowering_intensity', models.IntegerField(blank=True)),
                ('ripe_fruits', models.BooleanField(null=True)),
                ('senescence', models.BooleanField(null=True)),
                ('maintenance', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('done', models.BooleanField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.collection')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
    ]
