# Generated by Django 3.1.13 on 2021-09-07 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='collection',
            name='date',
            field=models.DateField(default=datetime.date(2021, 9, 7), help_text='Date and time of collection'),
        ),
        migrations.AddField(
            model_name='record',
            name='senescence_intensity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='flowering_intensity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp_edit',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 9, 58, 49, 348162, tzinfo=utc), help_text='Date and time of record edit'),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp_entry',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 9, 58, 49, 348149, tzinfo=utc), help_text='Date and time of record entry'),
        ),
    ]
