# Generated by Django 3.1.13 on 2023-03-07 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_collection_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 7), help_text='Date and time of collection'),
        ),
    ]
