# Generated by Django 3.1.13 on 2021-09-14 10:24

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_auto_20210914_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date and time of collection'),
        ),
        migrations.AlterField(
            model_name='record',
            name='maintenance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cut_partly', 'cut partly'), ('cut_total', 'cut total'), ('covered_natural', 'covered natural'), ('covered_artificial', 'covered artificial'), ('transplanted', 'transplanted'), ('removed', 'removed')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp_edit',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of record edit'),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp_entry',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of record entry'),
        ),
    ]
