# Generated by Django 3.1.13 on 2023-03-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_auto_20230307_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='no_observation',
            field=models.BooleanField(default=False),
        ),
    ]
