# Generated by Django 3.1.13 on 2021-12-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_auto_20210914_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='peak_flowering_estimation',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no')], max_length=2, null=True),
        ),
    ]
