# Generated by Django 3.1.13 on 2023-03-09 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_record_no_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 9), help_text='Date and time of collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='doy',
            field=models.IntegerField(default=68, help_text='Day of year'),
        ),
        migrations.AlterField(
            model_name='record',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='observations.collection'),
        ),
        migrations.AlterField(
            model_name='record',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='flowers_open',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no'), ('u', 'unsure')], default='no', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='initial_vegetative_growth',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no'), ('u', 'unsure'), ('m', 'missed')], default='no', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='peak_flowering',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no'), ('u', 'unsure')], default='no', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='peak_flowering_estimation',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no')], default='no', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ripe_fruits',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no'), ('u', 'unsure')], default='no', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='senescence',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no'), ('u', 'unsure')], default='no', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='young_leaves_unfolding',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('no', 'no'), ('u', 'unsure'), ('m', 'missed')], default='no', max_length=2, null=True),
        ),
    ]
