# Generated by Django 3.1.13 on 2023-03-14 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_auto_20230309_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 14), help_text='Date and time of collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='doy',
            field=models.IntegerField(default=73, help_text='Day of year'),
        ),
    ]
