# Generated by Django 3.1.13 on 2023-04-04 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_auto_20230314_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 4), help_text='Date and time of collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='doy',
            field=models.IntegerField(default=94, help_text='Day of year'),
        ),
    ]
