# Generated by Django 3.1.13 on 2021-09-06 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species', '0001_initial'),
        ('gardens', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden_name', models.CharField(help_text='Name used for the plant at the garden', max_length=100)),
                ('order', models.IntegerField(help_text='Order of the plant for the given garden')),
                ('active', models.BooleanField(help_text='Plant is actively observed or not')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.garden')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.species')),
            ],
            options={
                'unique_together': {('garden', 'order')},
            },
        ),
    ]
