# Generated by Django 3.1.13 on 2021-10-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='active',
            field=models.BooleanField(help_text='Plant is actively monitored or not'),
        ),
    ]
