# Generated by Django 3.1.13 on 2022-01-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('record', models.ForeignKey(help_text='Associated data record', on_delete=django.db.models.deletion.CASCADE, to='observations.record')),
            ],
        ),
    ]
