# Generated by Django 3.1.13 on 2021-08-18 10:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectors', '0001_initial'),
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('doy', models.IntegerField()),
                ('species', models.CharField(max_length=100)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collectors.collector')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gardens.garden')),
            ],
        ),
    ]
