# Generated by Django 3.1.13 on 2021-09-06 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='WGS 84', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='WGS 84', max_digits=9)),
                ('auth_groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Access groups')),
                ('auth_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Access users')),
            ],
        ),
    ]
