# Generated by Django 3.1.13 on 2023-04-04 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardens', '0002_auto_20230307_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='auth_users',
            field=models.ManyToManyField(blank=True, related_name='subgarden', to=settings.AUTH_USER_MODEL, verbose_name='Access users'),
        ),
    ]
