# Generated by Django 3.1.13 on 2021-08-18 15:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesGarden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('garden_name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gardens.garden')),
            ],
        ),
    ]
